name: Deploy moonerd.dev

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3.0.0
        with:
          node-version: '14'

      - name: Install packages
      - uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Generate sitemap
        run: sh script/generate-sitemap.sh

      - uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: build

  vercel:
    runs-on: ubuntu-latest
    name: 'Deploy front-end'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/

      - name: 'Deploy to Vercel'
        run: |
          prodRun=""
          if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
            prodRun="--prod"
          fi

          npx vercel --token ${VERCEL_TOKEN} $prodRun
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
